# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "FrontIn Natal 2016"
email: "jsdaybr@gmail.com"
description: "O JSday é um evento imersivo focado em Javascript e tudo o que essa linguagem tem a oferecer"
baseurl: ""
url: "http://jsday.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-62574701-1"
googleAnalyticsSiteUrl: "jsday.com.br"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "FrontIn Natal"
# organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "O JSday é um evento imersivo focado em Javascript e tudo o que essa linguagem tem a oferecer"
organizerEmail: "jsdaybr@gmail.com"
# organizerLogo: "/img/seo/organizer-logo.png"
# organizerLink: "http://fb.com/caravanaweb"

# Head
metaKeywords: "event, javascript, js, angularjs, google maps, ionic, firebase, aplicativos híbridos, nodebots"
twitterAccount: "@jsdaybr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/1TVsUN1L2xcMBK59MFnwW7X90Lw-gcj25_EVwnfTTu0U/viewform"
c4sponsorsUrl: "mailto:jsdaybr@gmail.com?subject=Patrocínio JSday Recife 2015"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
#  - {permalink: "/speakers/", text: "Palestrantes"}
#  - {permalink: "/schedule/", text: "Lineup"}
#  - {permalink: "/live/", text: "Live"}

bottomNavigationLinks:
 - {link: "http://even.tc/jsday-campina-grande-2016", text: "Inscreva-se"}
 - {link: "https://docs.google.com/forms/d/1TVsUN1L2xcMBK59MFnwW7X90Lw-gcj25_EVwnfTTu0U/viewform", text: "Call for Papers"}
rightNavigationButtons:
 - {link: "http://even.tc/jsday-campina-grande-2016", text: "Inscreva-se"}
 - {link: "https://docs.google.com/forms/d/1TVsUN1L2xcMBK59MFnwW7X90Lw-gcj25_EVwnfTTu0U/viewform", text: "Call for Papers"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Front In Natal: <typeout>"
eventDate: "23 de Abril, 2016"
typeoutTextValues: '"", "CSS", "HTML", "SASS", "AngularJS", "ES6"'
typeoutFallback: "JavaScript"
heroButtons:
 - {link: "http://even.tc/jsday-campina-grande-2016", text: "Inscreva-se"}
 - {link: "https://docs.google.com/forms/d/1TVsUN1L2xcMBK59MFnwW7X90Lw-gcj25_EVwnfTTu0U/viewform", text: "Call for Papers"}

# About Block
aboutTitle: "Sobre o Front In"
aboutBlock:
 - {title: "Evento", image: "javascript.jpg", text: "A Primeira edição do Front In em Natal, Com vários profissionais de renome no mercado." }
 - {title: "Mercado", image: "office.jpg", text: "O mercado tem uma demanda gigantesca por profissionais que conhecem as nuances do Javascript e estejam por dentro das novidades do ES6" }
 - {title: "Networking", image: "networking.jpg", text: "Uma das melhores formas para desenvolvimento profissional com certeza é conhecer a comunidade que você faz parte" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "participantes", detail: "num dos melhores teatros do nordeste"}
 - {count: "10", specialCharacter: "+", info: "horas", detail: "de puro código"}
 - {count: "5", specialCharacter: "+", info: "palestrantes", detail: "com tópicos incríveis"}

# Latest News Block
latestNewsTitle: "Novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 0
rockstarSpeakersTitle: "JavaScript Experts"
rockstarSpeakersButtonText: "Conheça todos Palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Teatro IFRN"
eventLocationLink: "http://www.cesed.br/portal/"
eventStreetAddress: "Av. Sen. Salgado Filho, 1559 - Lagoa Nova"
eventAddressLocality: "Natal"
eventAddressLocalityRegion: "RN"
eventPostalCode: "59015-000"
eventAddressCountry: "Brasil"
eventStartTime: "2016-23-04T08:00"
eventDoorTime: "08:00"
eventEndTime: "2016-23-04T18:00"
eventPlaceCoordinates: "-5.8115923,-35.2053576"
mapCenterCoordinates: "-5.8115923,-35.2053576"
mapMobileCenterCoordinates: "-5.8115923,-35.2053576"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Teatro IFRN"
venueFeatures: ["Capacidade para mais de 400 pessoas", "Um dos melhores teatros de Natal"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tweets.get()"
twitterHashTag: "jsdaybr"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Ajude-nos a codificar. Patrocine!"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Inscreva-se"
ticketsOffers:
 -
  name: "1º lote"
  price: "xx"
  priceCurrency: "R$"
  buyButtonLink: "http://even.tc/jsday-campina-grande-2016"
  buyButtonText: "Comprar"
  validFrom: "2015-10-05T10:00"
  validThrough: "2015-12-12T23:59"
 -
  name: "2º Lote"
  price: "2xx"
  priceCurrency: "R$"
  buyButtonLink: ""
  buyButtonText: "Não Disponível"
  validFrom: "2015-10-28T00:00"
  validThrough: "2015-12-11T23:59"
 -
  name: "3º"
  price: "3xx"
  priceCurrency: "R$"
  buyButtonLink: ""
  buyButtonText: "Não Disponível"
  validFrom: "2015-12-06T00:00"
  validThrough: "2015-12-12T06:00"

# Footer
socialLinks:
 # - {link: "https://twitter.com/intent/user?screen_name=jsdaybr", icon: "twitter"}
 - {link: "https://fb.com/Front-in-Natal-208844549494362/", icon: "facebook"}

footerBlocks:
 -
  title: "Links"
  links:
    - {link: "#", text: "UM LINK"}
    - {link: "#", text: "UM LINK"}
 -
  title: "Contato"
  links:
   - {link: "mailto:jsdaybr@gmail.com", text: "jsdaybr@gmail.com"}
 -
  title: "FAQ"
  links:
   - {link: "http://pt-br.confcodeofconduct.com/", text: "Código de Conduta"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Call for Papers
cfpTitle: "Espalhe o amor pelo JavaScript"
cfpDescription: "Uma oportunidade excelente para você mostrar do que o JavaScript é capaz, você já está por dentro das novidades do ES6, sabe como ninguém utilizar os componentes do ReactJS, programa usando JavaScript Funcional ou ainda quer explicar do que se trata esse tal de BabelJS. Siga os passos abaixo e envie sua proposta."

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false
