# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "FrontIn Natal 2016"
email: "contato@henrimichel.com.br"
description: ""
baseurl: ""
# url: "http://jsday.com.br"
# permalink: "/blog/:title"
# googleAnalyticsTrackingId: "UA-62574701-1"
# googleAnalyticsSiteUrl: "jsday.com.br"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "FrontInNatal"
# organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Já estava mais do que na hora de termos nossa edição deste evento que já está mais do que consolidado e aprovado pela comunidade FrontEnd. Já vimos FrontInPoa, FrontInFloripa, FrontInAracaju, FrontInBH, FrontInCuiaba, FrontInSM, FrontInBahia, FrontInMaceio e FrontInFortaleza e finalmente em 2016 estamos lançando o FrontInNatal. O evento é voltado para todo e qualquer estudante ou profissional da área de designer gráfico à desenvolvedor de software que atue na área de FrontEnd ou que deseje entrar neste mercado que cresce exponencialmente a cada dia que passa."
organizerEmail: "contato@henrimichel.com.br"
# organizerLogo: "/img/seo/organizer-logo.png"
# organizerLink: "http://fb.com/caravanaweb"

# Head
metaKeywords: "event, javascript, js, angularjs, google maps, ionic, firebase, aplicativos híbridos, nodebots"
twitterAccount: "#FrontInNatal"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"
#fbAppId: "464161153770183"
#fbAdminId: "1313798299"

# Documents

c4pUrl: "http://speakerfight.com/events/frontinnatal-2016/"
c4sponsorsUrl: "mailto:contato@henrimichel.com.br?subject=Patrocínio FrontInNatal 2016"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
#  - {permalink: "/speakers/", text: "Palestrantes"}
#  - {permalink: "/schedule/", text: "Lineup"}
#  - {permalink: "/live/", text: "Live"}

bottomNavigationLinks:
    - {link: "http://www.eventick.com.br/frontinnatal", text: "Inscreva-se"}
rightNavigationButtons:
    - {link: "http://www.eventick.com.br/frontinnatal", text: "Inscreva-se"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Front In Natal: <typeout>"
eventDate: "09 de Julho, 2016"
typeoutTextValues: '"", "CSS", "HTML", "SASS", "AngularJS", "ES6", "UX", "Design"'
typeoutFallback: "JavaScript"
heroButtons:
    - {link: "http://www.eventick.com.br/frontinnatal", text: "Inscreva-se"}

# About Block
aboutTitle: "Ei Coisinha, presta atenção."
aboutBlock:
 - {title: "Evento", image: "javascript.jpg", text: "A Primeira edição do FrontInNatal, Com vários profissionais de renome no mercado." }
 - {title: "Mercado", image: "office.jpg", text: "O mercado tem uma demanda gigantesca por profissionais que tenham conhecimentos específicos de tecnologias front end" }
 - {title: "Networking", image: "networking.jpg", text: "Uma das melhores formas para desenvolvimento profissional com certeza é conhecer a comunidade que você faz parte" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "participantes", detail: "no auditório principal do IFRN"}
 - {count: "10", specialCharacter: "+", info: "horas", detail: "de puro código"}
 - {count: "8", specialCharacter: "+", info: "palestrantes", detail: "com tópicos incríveis"}

# Latest News Block
latestNewsTitle: "Novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 0
rockstarSpeakersTitle: ""
rockstarSpeakersButtonText: "Conheça todos Palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Auditório Principal IFRN"
eventLocationLink: "http://portal.ifrn.edu.br/campus/natalcentral/"
eventStreetAddress: "Av. Sen. Salgado Filho, 1559 - Lagoa Nova"
eventAddressLocality: "Natal"
eventAddressLocalityRegion: "RN"
eventPostalCode: "59015-000"
eventAddressCountry: "Brasil"
eventStartTime: "2016-09-07T08:00"
eventDoorTime: "08:00"
eventEndTime: "2016-09-07T18:00"
eventPlaceCoordinates: "-5.8115923,-35.2053576"
mapCenterCoordinates: "-5.8115923,-35.2053576"
mapMobileCenterCoordinates: "-5.8115923,-35.2053576"

# Venue Block
venueBlockTitle: "Local"

venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Auditório IFRN"
venueFeatures: ["Capacidade para aproximadamente 500 participantes", "Um dos melhores auditórios de Natal"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tweets.get()"
twitterHashTag: "frontinnatal"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Dá uma mãozinha no evento. Patrocine"


# Tickets Block
ticketsTitle: "Inscreva-se"
ticketsOffers:
 -
  name: "1º lote"
  price: "70.00"
  priceCurrency: "R$"
  buyButtonLink: "http://portal.ifrn.edu.br/campus/natalcentral/"
  buyButtonText: "Comprar"
  validFrom: "2015-10-05T10:00"
  validThrough: "2016-09-06T23:59"
 -
  name: "2º Lote"
  price: "80.00"
  priceCurrency: "R$"
  buyButtonLink: "http://portal.ifrn.edu.br/campus/natalcentral/"
  buyButtonText: "Não Disponível"
  validFrom: "2016-10-06T00:00"
  validThrough: "2016-10-07T23:59"
 -
  name: "Estudante"
  price: "35.00"
  priceCurrency: "R$"
  buyButtonLink: "http://portal.ifrn.edu.br/campus/natalcentral/"
  buyButtonText: "Comprar"
  validFrom: "2015-12-06T00:00"
  validThrough: "2016-09-07T23:59"

# Footer
socialLinks:
 # - {link: "https://twitter.com/intent/user?screen_name=jsdaybr", icon: "twitter"}
 - {link: "https://fb.com/Front-in-Natal-208844549494362/", icon: "facebook"}

footerBlocks:
 # -
 #  title: "Links"
 #  links:
 #    - {link: "#", text: "UM LINK"}
 #    - {link: "#", text: "UM LINK"}
 -
  title: "Contato"
  links:
   - {link: "mailto:contato@henrimichel.com.br", text: "O Bunitão das tapioca"}
 -
  title: "FAQ"
  links:
   - {link: "http://pt-br.confcodeofconduct.com/", text: "Código de Conduta"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Call for Papers
cfpTitle: "Compartilhe conhecimento"
cfpDescription: "Tem vontade de expor seu conhecimento no evento? Evnie agora mesmo uma proposta de palestra em nosso Call4Papers"
